### ISSUE TITLE
placement of arrows for sorting

### ISSUE THREAD

**Issue by henrylyle** [uw-it-aca/retention-dashboard#139]
When I am in full screen mode the arrows for sorting are right in the middle of the space between each measure; for instance, activity and assignments. It’s unclear which measure I’m sorting by. When I go to half screen, they look like they should - tucked closer to each measure.

![image](https://user-images.githubusercontent.com/58445569/123304563-eb8ce700-d4d3-11eb-870a-c78e967ac868.png)

![image](https://user-images.githubusercontent.com/58445569/123304670-11b28700-d4d4-11eb-9f5c-561f7819f7f6.png)

**Comment by nick-falco** [comment]
![image](https://user-images.githubusercontent.com/20054276/123866647-f7711280-d8f2-11eb-9a7e-5ec5ba3f6a7c.png)

Fixed by removing class from table column definitions. See https://github.com/uw-it-aca/retention-dashboard/pull/150/commits/ccf618c1a179449df2eae361d712b895175e16a7.
